name: scan
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: checkout code
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version        
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: java -version
      - name: build frontend
        run: |
          cd frontend && npm install
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.1
        env:
          SYNOPSYS_SKIP_PHONE_HOME: true
        with:
          args: |
           '--blackduck.url="${{ secrets.BLACKDUCK_URL}}"  \
           --detect.project.name="nickstest" \
           --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" \
           --detect.excluded.detector.types=GIT \
           --detect.project.version.name="1.3-beta" \
           --detect.detector.search.depth=3 \
           --detect.blackduck.signature.scanner.exclusion.name.pattern=.git,node_modules \
           '

